version: '3'

services:
  server-node:
    container_name: node-react
    build: infra/web-server/node
    entrypoint: "/usr/local/bin/node-entrypoint.sh"
    tty: true
    volumes:
      - ./Project/v2/web:/app
    working_dir: /app
    ports:
      - '9001:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true